### ISSUE TITLE
Local Provider in TypeScript

### ISSUE THREAD

**Issue by ukstv** [glifio/wallet-provider#24]
Hey, I created a new provider: https://github.com/ukstv/local-filecoin-provider It uses local private key to generate an address. I believe it should live here, but my thing is written in TypeScript. What is the best approach to move it here? Rewrite in JS or translate filecoin-wallet-provider to TypeScript?

**Comment by Schwartz10** [comment]
Hey @ukstv the provider has been refactored to ts. Will close this for now.
